### PR TITLE
shower.min.js added to git

### PR DESCRIPTION
**Pull request by Zhomart**
Otherwise bower_components will not have shower.min.js file.

### CODE REVIEW

**Comment by pepelsbey** [comment]
I’d prefer to solve this problem some other way or even drop Bower support, what do you think @zloylos?

**Comment by Zhomart** [comment]
I think you don't need to drop bower support. For example, I'm developing simple express app that will have shower presentations in it. For browser side libraries I use bower, for server side I use npm. I don't want to make node_modules be available for public.
And shower is browser side library, I think it should be available in bower.

**Comment by pepelsbey** [comment]
I’ve always considered `node_modules` and `bower_components` as temporary folders that you can use for building production files, not just including them directly. For example, there’s no `node_modules` on [shwr.me](http://shwr.me/) site though it’s built from npm packages, [see Gruntfile](https://github.com/shower/shwr.me/blob/master/Gruntfile.js) that does all magic.

**Comment by Zhomart** [comment]
That is very peculiar method of doing it, replacing paths in each file. I'd like to do something simpler for both for development and production. I'm new to node.js, that's why I thought dividing to public/private  makes sense. I'm sure there are easier ways to do it using only npm.
Anyway, I'm going to continue using my fork of shower with bower.
If you don't want to support bower, you can close this issue.

**Pull request closed without merging**
