### PR TITLE
Fix listener removal.

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Every time `Function#bind` is called, a _new_ function is created. As a result, listeners were not removed (and duplicates were added). This pull request introduces the `util.bound` function, a memoized version of `bind`.

Also, it removes the obsolete `util.bind` function.

Dependency: shower/timer#3 (only place still using `util.bind`)

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
An alternative to this solution is implemented in [shower-touch](https://github.com/shower/touch/blob/3a2d6ff/shower-touch.js#L42-L43). We could replace that solution by the suggested `util.bound` (or the other way round).

**Comment by pepelsbey** [comment]
@zloylos, could you please review this PR?

@RubenVerborgh, thank you! The rest PRs will be addressed shortly.

**Comment by zloylos** [comment]
Looks good. This is really really an unfortunate mistake with listeners.

**Comment by RubenVerborgh** [comment]
Thanks for merging. Please don't forget shower/timer#3, or the timer breaks. (Actually, it is broken at the moment for another reason, but that PR fixes both :wink:)

**Pull request merged**
