### PR TITLE
Mark only last open .next item as active

### PR DESCRIPTION
**Pull request by varya**
I suppose that items made visible by `.next` magic class should not all be "active". Sometimes for customizing, it is needed to know which one of them was last shown. Semantically it is also usually one "active" element in the menu, list, etc. So, I re-made it so that only the last shown has `.active` class. The previous are marked with `.shown`. This would need defining this `.shown` class in themes.

### CODE REVIEW

**Comment by varya** [comment]
For the sale of backwards compatibility I keep all the `.active` but additionally mark the last activated with `.current`. No changes in themes are needed.

**Comment by pepelsbey** [comment]
[There’s an issue for that](https://github.com/shower/shower/issues/338) which proposed to solve it the same way but with different names. Would you mind adjusting your PR to fit the same principle that’s already used for slides?

**Comment by varya** [comment]
@pepelsbey What is your motivation for the proposed naming? It will require changes in themes. I suppose it's better to keep it as close to the current situation as possible. No problem of changing the names from my side but are you 100% sure?

**Comment by pepelsbey** [comment]
I don’t see people actively updating core without updating themes. Yes, there are custom ones, but it’s totally fine to use old core or update themes. This incompatibility is the price you pay for consistency.

**Comment by varya** [comment]
@pepelsbey I provided changes you suggested. This will require the following code change for the themes:

```diff
--- a/styles/slide/elements/next-full.scss
+++ b/styles/slide/elements/next-full.scss
@@ -6,7 +6,8 @@

        visibility:hidden;

-       &.active {
+       &.active,
+       &.visited {
                visibility:visible;
                }
```

**Comment by pepelsbey** [comment]
Thank you! Will review it on weekend.

**Comment by pepelsbey** [comment]
There’s [next-visited](https://github.com/shower/ribbon/compare/next-visited) branch with needed changes available both for ribbon and material themes. Once I’m done with testing I’ll merge this PR and release another 3.0 beta or might even the final release.

Off-topic: why are you still using the old Sass version? I guess it was heavily customized, right?

**Comment by pepelsbey** [comment]
@shvaikalesh could you please have a brief look?

**Comment by pepelsbey** [comment]
Hmm, I’d also mark the last item as visited once focus is moved to the next slide. Currently it stays “active”. Not sure if there’s a strong use case for this, but it seems logical.

next-visited

**Comment by varya** [comment]
@pepelsbey This diff is from my own theme, it does not have other version than Sass.

**Comment by varya** [comment]
@pepelsbey  In the referred issue the last visible item is not marked as visible. I coded as it was written there.

**Comment by pepelsbey** [comment]
Yes, I know we just haven’t discussed this back then. What do you think?

**Comment by varya** [comment]
I would make the active also `.visited`. But was there the reason why it was different in the issue?

**Comment by pepelsbey** [comment]
No reason at all. I just haven’t thought it through back then.

**Comment by varya** [comment]
@pepelsbey Fixed this.

**Pull request merged**
